<?php

namespace Application\Controllers;

use Application\Core\User;
use Phalcon\Mvc\View;
use Application\Models\Users;

class IndexController extends ControllerBase {
    private $message = null;

	public function beforeExecuteRoute($dispatcher)
    {
        parent::beforeExecuteRoute($dispatcher); // TODO: Change the autogenerated stub
    }

    public function addAction() 
    {
        $this->view->url_show = getenv( 'BASE_URI' );
    }
    
    public function registerAction()
    {
        $user = new Users();
        $user->username= $this->request->getPost("username");
        $user->fullname= $this->request->getPost("fullname");
        $user->phone= $this->request->getPost("phone");
        $user->email= $this->request->getPost("email");
        $this->view->disable();
        
        if (!$user->save()) {
            echo "Gagal Disimpan";
        } else{
            echo "Data Berhasil Diupdate";
        }
        $this->response->redirect(getenv( 'BASE_URI' ));
    }
    
    public function showAction()
    {
        $data_user = Users::find();
        $this->view->add = getenv( 'BASE_URI' ).'add';
        $this->view->data_user=$data_user;
    }

    public function editAction()
    {
        $id = $this->dispatcher->getParam("id");
        $user = Users::findFirst($id);
        
        $this->view->id=$user->id;
        $this->view->username= $user->username;
        $this->view->fullname= $user->fullname;
        $this->view->phone= $user->phone;
        $this->view->email= $user->email;
        $this->view->show = getenv( 'BASE_URI' );
    }

    public function updateAction()
   {
        $id = $this->request->getPost("id");
        $user = Users::findFirstById($id);
 
        $user->id = $id;
        $user->username= $this->request->getPost("username");
        $user->fullname= $this->request->getPost("fullname");
        $user->phone= $this->request->getPost("phone");
        $user->email= $this->request->getPost("email");
        $this->view->disable();
        
        if (!$user->save()) {
            echo "Gagal Disimpan";
        } else{
            echo "Data Berhasil Diupdate";
        }

        $this->response->redirect(getenv( 'BASE_URI' ));
   }

    public function delAction()
    {
        $id = $this->dispatcher->getParam("id");
        $user = Users::findFirst($id);
        $user->delete();

        return $this->response->redirect(getenv( 'BASE_URI' ));
    }

}

